apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels: 
    app: ui
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: henrychia1234/ui:latest
        ports:
        - containerPort: 80
